Add Compression bug to the list of known bugs
dotnet/core pull request #7910
Opened 2022-10-28 17:36 UTC by adamsitnik

cc @jeffhandley @Jozkee

2022-10-28 17:40 UTC, jeffhandley approved these changes

2022-10-28 17:42 UTC, jeffhandley commented
Let's actually hold off on merging this until we get the backport PR approved by Tactics. I'd like to add a statement about when it will be fixed.

2022-10-28 17:43 UTC, jeffhandley requested changes

2022-10-28 17:43 UTC, jeffhandley commented on release-notes/7.0/known-issues.md
> +It's impossible to decompress large (4GB+ after compression) zip archives that consist of more than one zipped file. There is no known workaround. More information and workaround can be found at: htt
```suggestion
It's impossible to decompress large (4GB+ after compression) zip archives that consist of more than one zipped file. There is no known workaround. More information and workaround can be found at: https://github.com/dotnet/runtime/issues/77159. This issue will be fixed in the December servicing release.
```

2022-10-29 04:07 UTC, Eryk1705 approved these changes

2022-10-29 18:45 UTC, merged