Polish release notes 1.x
dotnet/core pull request #8357
Opened 2023-04-05 20:04 UTC by Jay-o-Way

#8352

2023-04-05 22:16 UTC, Jay-o-Way commented
Hold on, i saw some things i have to fix

2023-04-06 00:08 UTC, mairaw requested changes
LGTM. Left a few comments. Didn't duplicate the same comment across all occcurrences.

2023-04-07 02:57 UTC, mairaw requested changes
Let's keep commit messages as-is unless display is messed up without the proper formatting.

2023-04-07 02:57 UTC, mairaw commented on release-notes/1.1/1.1-commits.md
> +- [`[91de2ce]`](https://github.com/dotnet/coreclr/commit/91de2ce) Record expr location for opaque value numbers
```suggestion
- [`[91de2ce]`](https://github.com/dotnet/coreclr/commit/91de2ce) Record expr location for opqaue value numbers
```

2023-04-07 02:57 UTC, mairaw commented on release-notes/1.1/1.1-commits.md
> +- [`[ab1d328]`](https://github.com/dotnet/coreclr/commit/ab1d328) Fix issue <https://github.com/dotnet/coreclr/issues/6600>
```suggestion
- [`[ab1d328]`](https://github.com/dotnet/coreclr/commit/ab1d328) Fix issue https://github.com/dotnet/coreclr/issues/6600
```

2023-04-07 02:57 UTC, mairaw commented on release-notes/1.1/1.1-commits.md
> +- [`[ac01e27]`](https://github.com/dotnet/coreclr/commit/ac01e27) Add link to <https://graphics.stanford.edu/~seander/bithacks.html#ZeroInWord> (#6430)
```suggestion
- [`[ac01e27]`](https://github.com/dotnet/coreclr/commit/ac01e27) Add link to https://graphics.stanford.edu/~seander/bithacks.html#ZeroInWord (#6430)
```

2023-04-07 02:57 UTC, mairaw commented on release-notes/1.1/1.1-commits.md
> +- [`[68a832d]`](https://github.com/dotnet/coreclr/commit/68a832d) Fix build issue <http://buildstatus/Issues/Issues.aspx?iid=802303>
```suggestion
- [`[68a832d]`](https://github.com/dotnet/coreclr/commit/68a832d) Fix build issue http://buildstatus/Issues/Issues.aspx?iid=802303
```

2023-04-07 02:57 UTC, mairaw commented on release-notes/1.1/1.1-commits.md
> +- [`[9130f83]`](https://github.com/dotnet/corefx/commit/9130f83) Fix for issue <https://github.com/dotnet/wcf/issues/1340> (DataContract special-handling of KeyValuePair generic type): data contracts
```suggestion
- [`[9130f83]`](https://github.com/dotnet/corefx/commit/9130f83) Fix for issue https://github.com/dotnet/wcf/issues/1340 (DataContract special-handling of KeyValuePair generic type): data contracts for the adapter and the original type do not get the same StableName (contract name)
```

2023-04-07 02:57 UTC, mairaw commented on release-notes/1.1/1.1-commits.md
> +- [`[dfe99ca]`](https://github.com/dotnet/cli/commit/dfe99ca) Port <https://github.com/dotnet/core-setup/pull/159> to CLI
```suggestion
- [`[dfe99ca]`](https://github.com/dotnet/cli/commit/dfe99ca) Port https://github.com/dotnet/core-setup/pull/159 to CLI
```

2023-04-07 02:57 UTC, mairaw commented on release-notes/1.1/1.1-commits.md
> +- [`[674312d]`](https://github.com/dotnet/wcf/commit/674312d) <http://dotnet-ci.cloudapp.net> -> <https://ci.dot.net>
```suggestion
- [`[674312d]`](https://github.com/dotnet/wcf/commit/674312d) http://dotnet-ci.cloudapp.net -> https://ci.dot.net
```

2023-04-07 02:57 UTC, mairaw commented on release-notes/1.1/1.1-commits.md
> +- [`[06047ee]`](https://github.com/dotnet/cli/commit/06047ee) Update only the ubuntu.14.04 dockerfile from <https://github.com/dotnet/core-setup/pull/58>
```suggestion
- [`[06047ee]`](https://github.com/dotnet/cli/commit/06047ee) Update only the ubuntu.14.04 dockerfile from https://github.com/dotnet/core-setup/pull/58
```

2023-04-07 02:57 UTC, mairaw commented on release-notes/1.1/1.1.5.md
> +* [`[0ac7078]`](https://github.com/dotnet/coreclr/commit/0ac7078) Port of <https://github.com/dotnet/coreclr/pull/12795> to release/1.1.0 (#12942)
```suggestion
* [`[0ac7078]`](https://github.com/dotnet/coreclr/commit/0ac7078) Port of https://github.com/dotnet/coreclr/pull/12795 to release/1.1.0 (#12942)
```

2023-04-08 14:15 UTC, Jay-o-Way commented
PTAL

2023-04-10 22:29 UTC, mairaw approved these changes

2023-04-10 22:29 UTC, merged