Polish release notes 8.x
dotnet/core pull request #8361
Opened 2023-04-05 20:11 UTC by Jay-o-Way

#8352

2023-04-05 20:40 UTC, mairaw commented
Can you resolve the conflicts here too?

2023-04-05 23:50 UTC, mairaw requested changes
Looks good. Just a suggestion for an improvement.

2023-04-05 23:50 UTC, mairaw commented on release-notes/8.0/install-windows.md
> +- To update an existing installation: ```winget upgrade```
```suggestion
- To install the .NET 8 runtime: `winget install dotnet-runtime-8`
- To install the .NET 8 SDK: `winget install dotnet-sdk-8`
- To update an existing installation: `winget upgrade`
```

2023-04-06 18:21 UTC, mairaw commented
I had already reviewed this PR and now it contain a bunch of extra files. Let's try to keep the PRs contained to avoid extra work.

2023-04-06 19:14 UTC, Jay-o-Way commented
Sorry. Saw something that concerned files from the other, already merged, folders. You guys are quicker then I'm used to, here. Should I (try to) move the last commit to a new branch? Or pay attention to this next time?

2023-04-06 20:13 UTC, mairaw commented
Just keep attention next time. Thanks!

2023-04-06 20:20 UTC, mairaw approved these changes

2023-04-06 20:20 UTC, merged